# Generated by Django 4.1.7 on 2023-03-06 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column_separator', models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon')], default=',', max_length=2)),
                ('string_character', models.CharField(choices=[("'", 'Quote'), ('"', 'Doublequote')], default='"', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('Full Name', 'Full Name'), ('Job', 'Job'), ('Email', 'Email'), ('Company', 'Company'), ('Integer', 'Integer'), ('Address', 'Address')], default='Integer', max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('range_from', models.PositiveIntegerField(blank=True, null=True)),
                ('range_to', models.PositiveIntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
